AllCops:
  TargetRubyVersion: 3.2.1

LineLength:
  Max: 100

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Lambda:
  EnforcedStyle: literal

Lint/AssignmentInCondition:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Gemspec/OrderedDependencies:
  Enabled: false
