AllCops:
  TargetRubyVersion: 2.4.3

LineLength:
  Max: 100

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Lambda:
  EnforcedStyle: literal

Lint/AssignmentInCondition:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Gemspec/OrderedDependencies:
  Enabled: false

# There is a bug in rubocop 0.52.1 (current version 2018-01-12),
# where time and date formats like "%d.%m%" are offenses
# see https://github.com/bbatsov/rubocop/issues/5223
Style/FormatStringToken:
  Enabled: false

